version: 0.0.{build}
skip_tags: true
build_script:
- ps: .\build.ps1
artifacts:
  - path: artifacts/packages/Release/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: ov1HE744hnP6J5umXYTQwuegvkI9qn4pNBZTsSvPO+9LOSktdYHTAnSUhMBZha/w
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master